package coremsg

const (
	MSG_FALLA_INFRAESTRUCTURA          = "MSG_FALLA_INFRAESTRUCTURA"
	MSG_ERROR_INICIO_APLICACION        = "MSG_ERROR_INICIO_APLICACION"
	MSG_ERROR_LEER_ARCHIVO             = "MSG_ERROR_LEER_ARCHIVO"
	MSG_ERROR_CONVERTIR_JSON_A_OBJECTO = "MSG_ERROR_CONVERTIR_JSON_A_OBJECTO"
)
