package coremsg

const (
	MSG_ERROR_INICIO_APLICACION        = "MSG_FALLA_INICIO_APLICACION"
	MSG_ERROR_BACKEND                  = "MSG_ERROR_BACKEND"
	MSG_ERROR_LEER_ARCHIVO             = "MSG_ERROR_LEER_ARCHIVO"
	MSG_ERROR_CONVERTIR_JSON_A_OBJECTO = "MSG_ERROR_CONVERTIR_JSON_A_OBJECTO"
)
