package coremsg

const (
	MSG_FALLA_INFRAESTRUCTURA          = "MSG_FALLA_INFRAESTRUCTURA"
	MSG_ERROR_INICIO_APLICACION        = "MSG_ERROR_INICIO_APLICACION"
	MSG_ERROR_LEER_ARCHIVO             = "MSG_ERROR_LEER_ARCHIVO"
	MSG_ERROR_CONVERTIR_JSON_A_OBJECTO = "MSG_ERROR_CONVERTIR_JSON_A_OBJECTO"
	MSG_ERROR_CONVERTIR_OBJETO_A_JSON  = "MSG_ERROR_CONVERTIR_OBJETO_A_JSON"
	MSG_ERROR_CONSTRUIR_REQUEST_API    = "MSG_ERROR_CONSTRUIR_REQUEST_API"
	MSG_ERROR_CONSUMIR_API             = "MSG_ERROR_CONSUMIR_API"
)
